### ISSUE TITLE
How can it work without the twilio.min.js file ?

### ISSUE THREAD

**Issue by onigetoc** [jefflinwood/TwilioClientPhoneGapExampleApp#1]
How can it work without the twilio.min.js file ?
If i don't include twilio.min.js script it doesn't work.

but if i add the http://static.twilio.com/libs/twiliojs/1.2/twilio.min.js
it work on my computer but not on a app created with Phonegap build on my Android.

**Comment by jefflinwood** [comment]
Hi,

It doesn't use the twilio.min.js javascript file if you are running it with PhoneGap - instead PhoneGap will add the tcPlugin.js javascript file to your project after you install the Twilio Client Plugin for PhoneGap.
